db:
  host: "localhost"
  port: 27017
  user: "bruno"
  pass: ""
  database: "bruno"

# AMQP server properties
server:
  host: "localhost"
  port: 8348
  user: "bruno"
  pass: ""
  exchange: "issue_tracker_exchange"
  queue: "issue_tracker_requests"